# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntest.proto\x12\x04test\"-\n\x0c\x46ieldOptions\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07options\x18\x02 \x03(\t\";\n\rConfigOptions\x12*\n\x0e\x63onfig_options\x18\x01 \x03(\x0b\x32\x12.test.FieldOptionsb\x06proto3')



_FIELDOPTIONS = DESCRIPTOR.message_types_by_name['FieldOptions']
_CONFIGOPTIONS = DESCRIPTOR.message_types_by_name['ConfigOptions']
FieldOptions = _reflection.GeneratedProtocolMessageType('FieldOptions', (_message.Message,), {
  'DESCRIPTOR' : _FIELDOPTIONS,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:test.FieldOptions)
  })
_sym_db.RegisterMessage(FieldOptions)

ConfigOptions = _reflection.GeneratedProtocolMessageType('ConfigOptions', (_message.Message,), {
  'DESCRIPTOR' : _CONFIGOPTIONS,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:test.ConfigOptions)
  })
_sym_db.RegisterMessage(ConfigOptions)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FIELDOPTIONS._serialized_start=20
  _FIELDOPTIONS._serialized_end=65
  _CONFIGOPTIONS._serialized_start=67
  _CONFIGOPTIONS._serialized_end=126
# @@protoc_insertion_point(module_scope)
